import "server-only";
import { createHmac, timingSafeEqual } from "node:crypto";

/**
 * Thin wrapper around Paystack's HTTP API — this project's sole payment
 * provider. Nothing here is specific to membership dues; it just knows how
 * to start a transaction, verify one, and check a webhook's signature.
 */

const PAYSTACK_BASE_URL = "https://api.paystack.co";

export function isPaystackConfigured(): boolean {
  return Boolean(process.env.PAYSTACK_SECRET_KEY);
}

function getSecretKey(): string {
  const key = process.env.PAYSTACK_SECRET_KEY;
  if (!key) throw new Error("PAYSTACK_SECRET_KEY is not set.");
  return key;
}

interface PaystackApiResponse<T> {
  status: boolean;
  message: string;
  data: T;
}

interface InitializeTransactionResult {
  authorizationUrl: string;
  accessCode: string;
  reference: string;
}

/**
 * Starts a transaction and returns the URL to send the browser to.
 *
 * `reference` is generated by the caller (not Paystack) specifically so a
 * DuesPayment row can exist — and be looked back up — before this call
 * ever completes. `amountPesewas` is the smallest currency unit (100 = GHS
 * 1.00), matching what Paystack's API itself expects and returns for GHS.
 */
export async function initializeTransaction(params: {
  email: string;
  amountPesewas: number;
  reference: string;
  callbackUrl: string;
  metadata?: Record<string, unknown>;
}): Promise<InitializeTransactionResult> {
  const response = await fetch(`${PAYSTACK_BASE_URL}/transaction/initialize`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${getSecretKey()}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      email: params.email,
      amount: params.amountPesewas,
      currency: "GHS",
      reference: params.reference,
      callback_url: params.callbackUrl,
      metadata: params.metadata,
    }),
  });

  const json = (await response.json().catch(() => null)) as PaystackApiResponse<{
    authorization_url: string;
    access_code: string;
    reference: string;
  }> | null;

  if (!response.ok || !json?.status) {
    console.error("[paystack] initialize failed", response.status, json?.message);
    throw new Error(json?.message || "Paystack could not start this payment.");
  }

  return {
    authorizationUrl: json.data.authorization_url,
    accessCode: json.data.access_code,
    reference: json.data.reference,
  };
}

export interface VerifyTransactionResult {
  status: "success" | "failed" | "abandoned" | string;
  amountPesewas: number;
  currency: string;
  paidAt: string | null;
  transactionId: number;
}

/**
 * Asks Paystack directly what a transaction's real status and amount are,
 * rather than trusting the reference alone. Used both after the browser
 * redirect back from Paystack and again inside the webhook handler — the
 * webhook's own payload is never trusted on its own for the same reason a
 * client-submitted price is never trusted: it names a reference, and this
 * confirms independently what actually happened to it.
 */
export async function verifyTransaction(reference: string): Promise<VerifyTransactionResult> {
  const response = await fetch(`${PAYSTACK_BASE_URL}/transaction/verify/${encodeURIComponent(reference)}`, {
    headers: { Authorization: `Bearer ${getSecretKey()}` },
  });

  const json = (await response.json().catch(() => null)) as PaystackApiResponse<{
    status: string;
    amount: number;
    currency: string;
    paid_at: string | null;
    id: number;
  }> | null;

  if (!response.ok || !json?.status) {
    console.error("[paystack] verify failed", response.status, json?.message);
    throw new Error(json?.message || "Paystack could not verify this payment.");
  }

  return {
    status: json.data.status,
    amountPesewas: json.data.amount,
    currency: json.data.currency,
    paidAt: json.data.paid_at,
    transactionId: json.data.id,
  };
}

/**
 * Paystack signs each webhook body with HMAC-SHA512 using the same secret
 * key, sent in the `x-paystack-signature` header. Verifying this is what
 * stops anyone who finds the webhook URL from posting a fake "payment
 * succeeded" event — without it, the endpoint would trust whatever it was
 * told. Compared with a constant-time check so response timing can't leak
 * information about a correct signature.
 */
export function verifyWebhookSignature(rawBody: string, signatureHeader: string | null): boolean {
  if (!signatureHeader) return false;
  const secretKey = process.env.PAYSTACK_SECRET_KEY;
  if (!secretKey) return false;

  const expected = createHmac("sha512", secretKey).update(rawBody).digest("hex");
  const expectedBuf = Buffer.from(expected, "utf8");
  const providedBuf = Buffer.from(signatureHeader, "utf8");
  if (expectedBuf.length !== providedBuf.length) return false;
  return timingSafeEqual(expectedBuf, providedBuf);
}
